/** Language extension → Monaco language ID map. */
export const EXT_TO_LANGUAGE: Record<string, string> = {
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  tsx: "typescript",
  mts: "typescript",
  cts: "typescript",
  json: "json",
  jsonc: "json",
  html: "html",
  htm: "html",
  xhtml: "html",
  css: "css",
  scss: "scss",
  less: "less",
  md: "markdown",
  mdx: "markdown",
  py: "python",
  pyw: "python",
  rs: "rust",
  go: "go",
  java: "java",
  c: "c",
  h: "c",
  cpp: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hxx: "cpp",
  cc: "cpp",
  xml: "xml",
  xsd: "xml",
  xsl: "xml",
  svg: "xml",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  psd1: "powershell",
  psm1: "powershell",
  sql: "sql",
  rb: "ruby",
  php: "php",
  phtml: "php",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  dart: "dart",
  lua: "lua",
  r: "r",
  rm: "r",
  rmd: "r",
  pl: "perl",
  pm: "perl",
  txt: "plaintext",
  log: "plaintext",
  csv: "plaintext",
  vue: "html",
  svelte: "html",
  astro: "html",
  graphql: "graphql",
  gql: "graphql",
  proto: "protobuf",
  dockerfile: "dockerfile",
  makefile: "makefile",
  cmake: "cmake",
  patch: "diff",
  diff: "diff",
};

/** Detect Monaco language ID from a file extension. */
export function detectLanguage(ext: string): string {
  return EXT_TO_LANGUAGE[ext.toLowerCase()] || "plaintext";
}
