export interface MenuItemDef {
  id: string;
  labelKey: string;
  shortcut?: string;
  disabled?: boolean;
  checked?: boolean;
  type?: "item" | "separator";
  children?: MenuItemDef[];
  /** Direct label text, bypasses i18n translation */
  label?: string;
}

// Helper
function sep(n: number): MenuItemDef {
  return { id: `_sep_${n}`, labelKey: "", type: "separator" };
}

let si = 0;
const S = () => sep(++si);

export interface MenuDef {
  id: string;
  labelKey: string;
  altKey: string;
  children: MenuItemDef[];
}

export const MENU_STRUCTURE: MenuDef[] = [
  {
    id: "file",
    labelKey: "menu.file",
    altKey: "f",
    children: [
      { id: "file.new", labelKey: "menu.file.new", shortcut: "Ctrl+N" },
      { id: "file.open", labelKey: "menu.file.open", shortcut: "Ctrl+O" },
      { id: "file.openFolder", labelKey: "menu.file.openFolder", shortcut: "Ctrl+Shift+O" },
      S(),
      { id: "file.save", labelKey: "menu.file.save", shortcut: "Ctrl+S" },
      { id: "file.saveAs", labelKey: "menu.file.saveAs", shortcut: "Ctrl+Shift+S" },
      { id: "file.saveAll", labelKey: "menu.file.saveAll" },
      S(),
      { id: "file.close", labelKey: "menu.file.close", shortcut: "Ctrl+W" },
      { id: "file.closeAll", labelKey: "menu.file.closeAll" },
      { id: "file.closeOthers", labelKey: "menu.file.closeOthers" },
      { id: "file.closeAllButCurrent", labelKey: "menu.file.closeAllButCurrent" },
      S(),
      { id: "file.reload", labelKey: "menu.file.reload" },
      S(),
      { id: "file.restoreLastClosed", labelKey: "menu.file.restoreLastClosed", shortcut: "Ctrl+Shift+T" },
      S(),
      { id: "file.saveSession", labelKey: "menu.file.saveSession" },
      { id: "file.loadSession", labelKey: "menu.file.loadSession" },
      S(),
      { id: "file.preferences", labelKey: "menu.file.preferences" },
      { id: "file.shortcutMapper", labelKey: "menu.file.shortcutMapper" },
      { id: "settings.editContextMenu", labelKey: "menu.file.editContextMenu" },
      S(),
      { id: "file.exit", labelKey: "menu.file.exit", shortcut: "Alt+F4" },
    ],
  },
  {
    id: "edit",
    labelKey: "menu.edit",
    altKey: "e",
    children: [
      { id: "edit.undo", labelKey: "menu.edit.undo", shortcut: "Ctrl+Z" },
      { id: "edit.redo", labelKey: "menu.edit.redo", shortcut: "Ctrl+Y" },
      S(),
      { id: "edit.cut", labelKey: "menu.edit.cut", shortcut: "Ctrl+X" },
      { id: "edit.copy", labelKey: "menu.edit.copy", shortcut: "Ctrl+C" },
      { id: "edit.paste", labelKey: "menu.edit.paste", shortcut: "Ctrl+V" },
      { id: "edit.delete", labelKey: "menu.edit.delete", shortcut: "Del" },
      { id: "edit.selectAll", labelKey: "menu.edit.selectAll", shortcut: "Ctrl+A" },
      S(),
      { id: "edit.duplicateLine", labelKey: "menu.edit.duplicateLine", shortcut: "Ctrl+D" },
      { id: "edit.deleteLine", labelKey: "menu.edit.deleteLine", shortcut: "Ctrl+L" },
      { id: "edit.moveLineUp", labelKey: "menu.edit.moveLineUp", shortcut: "Ctrl+Shift+Up" },
      { id: "edit.moveLineDown", labelKey: "menu.edit.moveLineDown", shortcut: "Ctrl+Shift+Down" },
      S(),
      { id: "edit.columnMode", labelKey: "menu.edit.columnMode" },
      S(),
      { id: "edit.trimTrailing", labelKey: "menu.edit.trimTrailing" },
      { id: "edit.removeEmptyLines", labelKey: "menu.edit.removeEmptyLines" },
      S(),
      { id: "edit.toUpper", labelKey: "menu.edit.toUpper" },
      { id: "edit.toLower", labelKey: "menu.edit.toLower" },
      S(),
      { id: "edit.copyFilePath", labelKey: "menu.edit.copyFilePath" },
      { id: "edit.copyFileName", labelKey: "menu.edit.copyFileName" },
      { id: "edit.copyDirPath", labelKey: "menu.edit.copyDirPath" },
      S(),
      { id: "edit.insertDateTime", labelKey: "menu.edit.insertDateTime" },
      S(),
      { id: "edit.sortAscending", labelKey: "menu.edit.sortAscending" },
      { id: "edit.sortDescending", labelKey: "menu.edit.sortDescending" },
      { id: "edit.removeDupLines", labelKey: "menu.edit.removeDupLines" },
      S(),
      { id: "edit.splitLines", labelKey: "menu.edit.splitLines", shortcut: "Ctrl+I" },
      { id: "edit.joinLines", labelKey: "menu.edit.joinLines", shortcut: "Ctrl+J" },
      S(),
      { id: "edit.tab2Space", labelKey: "menu.edit.tab2Space" },
      { id: "edit.space2TabLeading", labelKey: "menu.edit.space2TabLeading" },
      { id: "edit.space2TabAll", labelKey: "menu.edit.space2TabAll" },
      S(),
      { id: "edit.formatXml", labelKey: "menu.edit.formatXml" },
      { id: "edit.validateXml", labelKey: "menu.edit.validateXml" },
      S(),
      { id: "edit.commentToggle", labelKey: "menu.edit.commentToggle" },
      { id: "edit.blockComment", labelKey: "menu.edit.blockComment" },
      { id: "edit.blockUncomment", labelKey: "menu.edit.blockUncomment" },
    ],
  },
  {
    id: "search",
    labelKey: "menu.search",
    altKey: "s",
    children: [
      { id: "search.find", labelKey: "menu.search.find", shortcut: "Ctrl+F" },
      { id: "search.findNext", labelKey: "menu.search.findNext", shortcut: "F3" },
      { id: "search.findPrev", labelKey: "menu.search.findPrev", shortcut: "Shift+F3" },
      { id: "search.replace", labelKey: "menu.search.replace", shortcut: "Ctrl+H" },
      S(),
      { id: "search.goTo", labelKey: "menu.search.goTo", shortcut: "Ctrl+G" },
      S(),
      { id: "search.findInFiles", labelKey: "menu.search.findInFiles", shortcut: "Ctrl+Shift+F" },
      S(),
      { id: "search.markAll", labelKey: "menu.search.markAll" },
      S(),
      // ── Bookmarks ──
      { id: "search.toggleBookmark", labelKey: "menu.search.toggleBookmark" },
      { id: "search.nextBookmark", labelKey: "menu.search.nextBookmark" },
      { id: "search.prevBookmark", labelKey: "menu.search.prevBookmark" },
      { id: "search.clearBookmarks", labelKey: "menu.search.clearBookmarks" },
      S(),
      // ── Bracket matching ──
      { id: "search.gotoMatchingBrace", labelKey: "menu.search.gotoMatchingBrace" },
      { id: "search.selectMatchingBraces", labelKey: "menu.search.selectMatchingBraces" },
      S(),
      // ── Mark submenu ──
      {
        id: "search.markSubmenu",
        labelKey: "menu.search.mark",
        children: [
          { id: "search.markAllStyle1", labelKey: "menu.search.markAllStyle1" },
          { id: "search.markAllStyle2", labelKey: "menu.search.markAllStyle2" },
          { id: "search.markAllStyle3", labelKey: "menu.search.markAllStyle3" },
          { id: "search.markAllStyle4", labelKey: "menu.search.markAllStyle4" },
          { id: "search.markAllStyle5", labelKey: "menu.search.markAllStyle5" },
          S(),
          { id: "search.unmarkAllStyle1", labelKey: "menu.search.unmarkAllStyle1" },
          { id: "search.unmarkAllStyle2", labelKey: "menu.search.unmarkAllStyle2" },
          { id: "search.unmarkAllStyle3", labelKey: "menu.search.unmarkAllStyle3" },
          { id: "search.unmarkAllStyle4", labelKey: "menu.search.unmarkAllStyle4" },
          { id: "search.unmarkAllStyle5", labelKey: "menu.search.unmarkAllStyle5" },
          S(),
          { id: "search.clearAllMarks", labelKey: "menu.search.clearAllMarks" },
          { id: "search.inverseMarksStyle1", labelKey: "menu.search.inverseMarksStyle1" },
        ],
      },
      S(),
      { id: "search.cutMarkedLines", labelKey: "menu.search.cutMarkedLines" },
      { id: "search.copyMarkedLines", labelKey: "menu.search.copyMarkedLines" },
      { id: "search.pasteMarkedLines", labelKey: "menu.search.pasteMarkedLines" },
      { id: "search.deleteMarkedLines", labelKey: "menu.search.deleteMarkedLines" },
      S(),
      { id: "search.gotoNextMarkStyle1", labelKey: "menu.search.gotoNextMarkStyle1" },
      { id: "search.gotoNextMarkStyle2", labelKey: "menu.search.gotoNextMarkStyle2" },
      { id: "search.gotoNextMarkStyle3", labelKey: "menu.search.gotoNextMarkStyle3" },
      { id: "search.gotoNextMarkStyle4", labelKey: "menu.search.gotoNextMarkStyle4" },
      { id: "search.gotoNextMarkStyle5", labelKey: "menu.search.gotoNextMarkStyle5" },
      S(),
      { id: "search.gotoPrevMarkStyle1", labelKey: "menu.search.gotoPrevMarkStyle1" },
      { id: "search.gotoPrevMarkStyle2", labelKey: "menu.search.gotoPrevMarkStyle2" },
      { id: "search.gotoPrevMarkStyle3", labelKey: "menu.search.gotoPrevMarkStyle3" },
      { id: "search.gotoPrevMarkStyle4", labelKey: "menu.search.gotoPrevMarkStyle4" },
      { id: "search.gotoPrevMarkStyle5", labelKey: "menu.search.gotoPrevMarkStyle5" },
    ],
  },
  {
    id: "view",
    labelKey: "menu.view",
    altKey: "v",
    children: [
      { id: "view.wordWrap", labelKey: "menu.view.wordWrap" },
      { id: "view.showWhitespace", labelKey: "menu.view.showWhitespace" },
      { id: "view.showIndentGuides", labelKey: "menu.view.showIndentGuide" },
      { id: "view.showLineNumbers", labelKey: "menu.view.showLineNumbers" },
      { id: "view.showMinimap", labelKey: "menu.view.showMinimap" },
      S(),
      { id: "view.foldAll", labelKey: "menu.view.foldAll" },
      { id: "view.unfoldAll", labelKey: "menu.view.unfoldAll" },
      S(),
      { id: "view.zoomIn", labelKey: "menu.view.zoomIn", shortcut: "Ctrl++" },
      { id: "view.zoomOut", labelKey: "menu.view.zoomOut", shortcut: "Ctrl+-" },
      { id: "view.zoomReset", labelKey: "menu.view.zoomReset", shortcut: "Ctrl+0" },
      S(),
      { id: "view.fullScreen", labelKey: "menu.view.fullScreen", shortcut: "F11" },
      S(),
      { id: "view.splitNone", labelKey: "menu.view.splitNone" },
      { id: "view.splitHorizontal", labelKey: "menu.view.splitHorizontal" },
      { id: "view.splitVertical", labelKey: "menu.view.splitVertical" },
      S(),
      { id: "view.alwaysOnTop", labelKey: "menu.view.alwaysOnTop" },
      S(),
      { id: "view.toggleSidebar", labelKey: "menu.view.toggleSidebar" },
      S(),
      { id: "view.distractionFree", labelKey: "menu.view.distractionFree", shortcut: "F12" },
      S(),
      { id: "view.summary", labelKey: "menu.view.summary" },
    ],
  },
  {
    id: "encoding",
    labelKey: "menu.encoding",
    altKey: "n",
    children: [
      { id: "encoding.encodeUtf8", labelKey: "menu.encoding.encodeUtf8" },
      { id: "encoding.encodeUtf8Bom", labelKey: "menu.encoding.encodeUtf8Bom" },
      { id: "encoding.convertUtf8", labelKey: "menu.encoding.convertUtf8" },
      { id: "encoding.convertUtf8Bom", labelKey: "menu.encoding.convertUtf8Bom" },
      S(),
      { id: "encoding.convertAnsi", labelKey: "menu.encoding.convertAnsi" },
      { id: "encoding.convertUtf16LE", labelKey: "menu.encoding.convertUtf16LE" },
      { id: "encoding.convertUtf16BE", labelKey: "menu.encoding.convertUtf16BE" },
      S(),
      { id: "encoding.openDialog", labelKey: "menu.encoding.openDialog" },
    ],
  },
  {
    id: "language",
    labelKey: "menu.language",
    altKey: "l",
    children: [
      { id: "lang.plaintext", labelKey: "menu.language.plaintext" },
      S(),
      { id: "lang.javascript", labelKey: "menu.language.javascript" },
      { id: "lang.typescript", labelKey: "menu.language.typescript" },
      { id: "lang.json", labelKey: "menu.language.json" },
      { id: "lang.html", labelKey: "menu.language.html" },
      { id: "lang.css", labelKey: "menu.language.css" },
      S(),
      { id: "lang.python", labelKey: "menu.language.python" },
      { id: "lang.rust", labelKey: "menu.language.rust" },
      { id: "lang.go", labelKey: "menu.language.go" },
      { id: "lang.java", labelKey: "menu.language.java" },
      { id: "lang.c", labelKey: "menu.language.c" },
      { id: "lang.cpp", labelKey: "menu.language.cpp" },
      S(),
      { id: "lang.xml", labelKey: "menu.language.xml" },
      { id: "lang.yaml", labelKey: "menu.language.yaml" },
      { id: "lang.markdown", labelKey: "menu.language.markdown" },
      { id: "lang.sql", labelKey: "menu.language.sql" },
      { id: "lang.shell", labelKey: "menu.language.shell" },
      S(),
      { id: "language.defineLanguage", labelKey: "menu.language.defineLanguage" },
      S(),
      { id: "language.openUdlFolder", labelKey: "menu.language.openUdlFolder" },
    ],
  },
  {
    id: "macro",
    labelKey: "menu.macro",
    altKey: "m",
    children: [
      { id: "macro.startRecord", labelKey: "menu.macro.startRecord" },
      { id: "macro.stopRecord", labelKey: "menu.macro.stopRecord" },
      { id: "macro.playback", labelKey: "menu.macro.playback" },
      S(),
      { id: "macro.save", labelKey: "menu.macro.save" },
    ],
  },
  {
    id: "run",
    labelKey: "menu.run",
    altKey: "r",
    children: [
      { id: "run.dialog", labelKey: "menu.run.dialog" },
      S(),
      { id: "run.openTerminal", labelKey: "menu.run.openTerminal" },
      { id: "run.claudeCode", labelKey: "menu.run.claudeCode", shortcut: "Ctrl+Alt+C" },
      { id: "run.codex", labelKey: "menu.run.codex", shortcut: "Ctrl+Alt+X" },
    ],
  },
  {
    id: "tools",
    labelKey: "menu.tools",
    altKey: "t",
    children: [
      { id: "tool.md5Generate", labelKey: "menu.tools.md5" },
      { id: "tool.sha1Generate", labelKey: "menu.tools.sha1" },
      { id: "tool.sha256Generate", labelKey: "menu.tools.sha256" },
      { id: "tool.sha512Generate", labelKey: "menu.tools.sha512" },
    ],
  },
  {
    id: "window",
    labelKey: "menu.window",
    altKey: "w",
    children: [
      { id: "window.nextTab", labelKey: "menu.window.nextTab", shortcut: "Ctrl+Tab" },
      { id: "window.prevTab", labelKey: "menu.window.prevTab", shortcut: "Ctrl+Shift+Tab" },
      S(),
      { id: "window.close", labelKey: "menu.window.close", shortcut: "Ctrl+W" },
      { id: "window.closeAll", labelKey: "menu.window.closeAll" },
    ],
  },
  {
    id: "plugins",
    labelKey: "menu.plugins",
    altKey: "p",
    children: [
      { id: "plugins.compare", labelKey: "menu.compare" },
      { id: "plugins.manager", labelKey: "plugin.title" },
    ],
  },
  {
    id: "help",
    labelKey: "menu.help",
    altKey: "h",
    children: [
      { id: "help.checkUpdate", labelKey: "menu.help.checkUpdate" },
      S(),
      { id: "help.about", labelKey: "menu.help.about" },
    ],
  },
];

/** Dispatch a menu action via a single custom event. */
export function dispatchMenuAction(actionId: string): void {
  window.dispatchEvent(new CustomEvent("menu-action", { detail: actionId }));
}
